<?php namespace ProcessWire;

class PadSmartShippingProducts extends WireData implements Module {
  public static function getModuleInfo() {
    return array(
      'title' => 'PadSmartShipping - Stock Product infos',
      'version' => 1,
      'summary' => 'Add stock-related fields to the products',
      'icon' => 'cart-plus',
      'href' => 'https://github.com/jvaubourg/processwire-module-padsmartshipping',
      'author' => 'Julien Vaubourg',
      'permission' => 'padloper-admin',
      'permissions' => 'padloper-admin',
      'requires' => [ 'PadSmartShippingCountries', 'PadSmartShippingWarehouses', 'InputfieldTable' ],
    );
  }

  public function calculateVat($product_price, $warehouse_country, $vatrate, $dst_country_code) {
//    $warehouse_country_code = $warehouse_country->pad_smartshipping_country_code;
//
//    if($warehouse_country_code == 'DE') {
//      $warehouse_in_dst_country = $this->pages->get("template=padsmartshipping_country, code=${dst_country_code}");
//
//      if($warehouse_in_dst_country instanceof NullPage) {
//        $vat_percentage = 
//        return $product_price * ($vat_percentage / 100);
//
//      } else {
//        return $product_price * ($vatrate / 100);
//      }
//    } else {
//
//    }
  }

  public function getPriceWithVat($product, $dst_country_code) {
    $pricefield = $event->object->pricefield;
    $product_price = $product->$pricefield;

    $stocks = $this->pages->find("template=padsmartshipping_product_stock, parent=${product}");

    foreach($stocks as $stock) {
      $warehouse = $stock->pad_smartshipping_product_stock_warehouse;
      $vatrate = $stock->pad_smartshipping_product_stock_vatrate;
      $warehouse_country = $warehouse->pad_smartshipping_warehouse_country;

      if($warehouse_country->pad_smartshipping_country_code == $dst_country_code) {
        return $product_price + $this->calculateVat($product_price, $warehouse_country, $vatrate, $dst_country_code);
      }

      $warehouse_shippingmethods = $warehouse->pad_smartshipping_warehouse_shippingmethods;
      $warehouse_shippingmethod = $warehouse_shippingmethods->get("pad_smartshipping_warehouse_shippingmethod_countries*=${dst_country_code}");

      if(!($warehouse_shippingmethod instanceof NullPage)) {
        return $product_price + $this->calculateVat($product_price, $warehouse_country, $vatrate, $dst_country_code);
      }
    }

    return -1;
  }

  // inspired from PadProcessShipping
  public function install() {
    $fields = $this->getFieldData();
    $field_names = '';

    $vatrates_country_template = $this->templates->get('padsmartshipping_country');
    $fields['pad_smartshipping_product_vatrates']['col1selector'] = 'template=' . $vatrates_country_template->id;

    $vatrates_category_list = file_get_contents(__DIR__ . '/data/vatrates_list.txt');
    $fields['pad_smartshipping_product_vatrates']['col2options'] = $vatrates_category_list;

    $stocks_warehouse_template = $this->templates->get('padsmartshipping_warehouse');
    $fields['pad_smartshipping_product_stocks']['col1selector'] = 'template=' . $stocks_warehouse_template->id;

    foreach($fields as $field_name => $field_data) {
      $f = new Field();
      $f->setImportData($field_data);
      $f->save();
      $field_names .= "$field_name ";
    }

    $this->message("Created fields $field_names");

    $templates = $this->getTemplateData();
    $template_names = '';

    foreach($templates as $template_name => $template_data) {
      $fg = new Fieldgroup();
      $fg->name = $template_name;
      $template_names .= "$template_name ";

      foreach($template_data['fieldgroupFields'] as $fieldname) {
        $fg->add($fieldname);
      }

      $fg->save();

      $t = new Template();
      $t->setImportData($template_data) ;
      $t->save();
    }

    $this->message("Created templates $template_names");

    foreach($this->modules->get('PadCart')->product_templates as $tpl) {
      $product_tpl = $this->templates->get($tpl);

      $product_tpl->fields->add($this->fields->get('pad_smartshipping_product_weight'));
      $product_tpl->fields->add($this->fields->get('pad_smartshipping_product_volume'));
      $product_tpl->fields->add($this->fields->get('pad_smartshipping_product_stocks'));
      $product_tpl->fields->save();

      // ref to the PadOpt module here
      if($product_tpl->name == 'product') {
        $product_fg = $this->fieldgroups->get($product_tpl->name);

        $product_tpl->fields->add($this->fields->get('pad_smartshipping_product_vatrates'));
        $product_tpl->fields->save();

        $product_fg->setFieldContextArray($product_fg->getField('variations', true)->id, [ 'requiredIf' => 'padopt_tpl_id=""', 'showIf' => 'padopt_tpl_id=""' ]);
        $product_fg->setFieldContextArray($product_fg->getField('pad_smartshipping_product_weight', true)->id, [ 'requiredIf' => "padopt_tpl_id!=''", 'showIf' => "padopt_tpl_id!=''" ]);
        $product_fg->setFieldContextArray($product_fg->getField('pad_smartshipping_product_volume', true)->id, [ 'requiredIf' => "padopt_tpl_id!=''", 'showIf' => "padopt_tpl_id!=''" ]);
        $product_fg->setFieldContextArray($product_fg->getField('pad_smartshipping_product_stocks', true)->id, [ 'requiredIf' => "padopt_tpl_id!=''", 'showIf' => "padopt_tpl_id!=''" ]);

        $product_fg->saveContext();
      }

      $this->message("Added product fields to the {$product_tpl->name} product template");
    }
  }

  public function uninstall() {
//    $padpages = $this->pages->find("template=padsmartshipping_product_stock, include=all");
//
//    foreach($padpages as $p) {
//      if($p->id) $this->pages->delete($p, true);
//    }

    foreach($this->modules->get('PadCart')->product_templates as $tpl) {
      $product_tpl = $this->templates->get($tpl);

      // ref to the PadOpt module here
      if($product_tpl->name == 'product') {
        $product_tpl->fields->remove($this->fields->get('pad_smartshipping_product_vatrates'));

        $product_fg = $this->fieldgroups->get($product_tpl->name);
        $product_fg->setFieldContextArray($product_fg->getField('variations', true)->id, []);
        $product_fg->saveContext();
      }

      $product_tpl->fields->remove($this->fields->get('pad_smartshipping_product_stocks'));
      $product_tpl->fields->remove($this->fields->get('pad_smartshipping_product_volume'));
      $product_tpl->fields->remove($this->fields->get('pad_smartshipping_product_weight'));
      $product_tpl->fields->save();
    }

    $templates = $this->getTemplateData();

    foreach($templates as $template_name => $template_data) {
      $t = $this->templates->get($template_name);
      if($t) $this->templates->delete($t);
      $fg = $this->fieldgroups->get($template_name);
      if($fg) $this->fieldgroups->delete($fg);
    }

    $fields = $this->getFieldData();

    foreach($fields as $field_name => $field_data) {
      $f = $this->fields->get($field_name);
      if($f) {
        $f->flags = Field::flagSystemOverride;
        $f->flags = 0;
        $this->fields->delete($f);
      }
    }
  }

  private function getFieldData() {
    $fields_json = file_get_contents(__DIR__ . "/data/products_fields.json");
    return json_decode($fields_json, true);
  }

  private function getTemplateData() {
    $templates_json = file_get_contents(__DIR__ . "/data/products_templates.json");
    return json_decode($templates_json, true);
  }
}
