<?php namespace ProcessWire;

class PadSmartShippingWarehouses extends Process Implements WirePageEditor {
  public static function getModuleInfo() {
    return array(
      'title' => 'PadSmartShipping - List of Warehouses with Shipping Methods',
      'version' => 1,
      'summary' => 'Add an admin menu to define warehouses with available shipping methods',
      'icon' => 'cart-plus',
      'href' => 'https://github.com/jvaubourg/processwire-module-padsmartshipping',
      'author' => 'Julien Vaubourg',
      'permission' => 'padloper-admin',
      'permissions' => 'padloper-admin',
      'requires' => [ 'PadSmartShippingCountries', 'InputfieldTable' ],
      'page' => array(
        'name' => 'padsmartshipping-warehouses',
        'parent' => 'setup',
        'title' => 'SmartShipping Warehouses',
      ),
    );
  }

  public function execute() {
    $scripts = __DIR__ . "/PadProcessTabs.js";
    $this->config->scripts->add($scripts);
    
    $this->modules->get('JqueryWireTabs');
    $wrapper = new InputfieldWrapper();
    $wrapper->attr('class', 'ui-helper-clearfix');

    $warehouses = $this->pages->find("template=padsmartshipping_warehouse");

    foreach($warehouses as $warehouse) {
      $tab = new InputfieldWrapper();
      $tab->attr('id', $warehouse->name);
      $tab->attr('title', $warehouse->title);
      $tab->attr('class', 'WireTab');

      $markup = $this->modules->get('InputfieldMarkup');
      $markup->label = $warehouse->title;
      $markup->icon = 'globe';

      $button = $this->modules->get('InputfieldButton');
      $button->attr('href', "./edit/?id={$warehouse->id}");
      $button->attr('icon', 'truck');
      $button->attr('value', $this->_("Edit Shipping Methods"));

      if($warehouse->pad_smartshipping_warehouse_shippingmethods->count) {
        $table = $this->modules->get('MarkupAdminDataTable');
        $table->setEncodeEntities(false);
        $fields = $warehouse->pad_smartshipping_warehouse_shippingmethods->first()->fields;
        $headerFields = array();

        foreach($fields as $field) {
          $headerFields[] = $field->label;
        }

        $table->headerRow($headerFields);

        foreach($warehouse->pad_smartshipping_warehouse_shippingmethods as $ptr) {
          $fieldValues = array();

          foreach($ptr->fields as $field) {
            $fieldValues[] = $ptr->get($field->name);
          }

          $table->row($fieldValues);
        }

        $markup->value .= '<br />' . $table->render();

      } else {
        $button->attr('value', $this->_("Add Shipping methods"));
        $message = $this->_("This warehouse doesn't have shopping methods yet.");
        $markup->value .= "<p class='description'>$message</p>";
      }
      
      $markup->value .= $button->render();
      $tab->add($markup);
      $wrapper->add($tab);
    }

    $button = $this->modules->get('InputfieldButton');
    $button->attr('wrapClass', 'ui-helper-clearfix');
    $button->attr('href', './edit/?id=0');
    $button->attr('icon', 'plus-circle');
    $button->attr('value', $this->_("Add new Warehouse"));

    $out = $wrapper->render();
    $out .= '<br />';
    $out .= $button->render();

    return $out;
  }

  public function executeEdit() {
    $this->breadcrumbs->add(new Breadcrumb('../', $this->page->title));

    $warehouse = $this->pages->get((int) $this->input->get('id'));

    if($warehouse->id > 0) {
      Wire::setFuel('processHeadline', $this->_("Edit Warehouse:") . " {$warehouse->title}");

    } else {
      Wire::setFuel('processHeadline', $this->_("Add new Warehouse"));

      $warehouse = new Page();
      $warehouse->template = 'padsmartshipping_warehouse';
      $warehouse->parent = $this->pages->get('template=admin, name=padsmartshipping-warehouses');
      $warehouse->title = $this->_("New warehouse class");
      $warehouse->save();

      $this->session->redirect("./?id={$warehouse->id}");
    }

    $pe = $this->modules->get('ProcessPageEdit');
    
    return $pe->execute();
  }

  public function getPage() {
    return $this->page;
  }

  public function getCountriesList() {
    include(__DIR__ . '/data/countries_list.php');
    return $countries_list;
  }

  // inspired from PadProcessShipping
  public function install() {
    parent::install();

    $fields = $this->getFieldData();
    $field_names = '';

    foreach($fields as $field_name => $field_data) {
      $f = new Field();

      $f->setImportData($field_data);
      $f->save();
      $field_names .= "$field_name ";
    }

    $countries_list = array_keys($this->getCountriesList());

    $countries_values = array('0=WORLD', '1=EUROPE');
    for($i = 0; $i < count($countries_list); $i++) {
      $countries_values[] = ($i + 3) . "=${countries_list[$i]}";
    }

    $field = $this->fields->get('pad_smartshipping_warehouse_shippingmethod_incountries');
    $this->modules->get('FieldtypeOptions')->manager->setOptionsString($field, implode("\n", $countries_values), true);

    $countries_values = array();
    for($i = 0; $i < count($countries_list); $i++) {
      $countries_values[] = ($i + 1) . "=${countries_list[$i]}";
    }

    $field = $this->fields->get('pad_smartshipping_warehouse_shippingmethod_excountries');
    $this->modules->get('FieldtypeOptions')->manager->setOptionsString($field, implode("\n", $countries_values), true);

    $this->message("Created fields $field_names");

    $templates = $this->getTemplateData();
    $template_names = '';

    foreach($templates as $template_name => $template_data) {
      $fg = new Fieldgroup();
      $fg->name = $template_name;
      $template_names .= "$template_name ";

      foreach($template_data['fieldgroupFields'] as $fieldname) {
        $fg->add($fieldname);
      }

      $fg->save();

      $t = new Template();
      $t->setImportData($template_data) ;
      $t->save();
    }

    $this->message("Created templates $template_names");

    $shippingmethods_pagetable = $this->fields->get("pad_smartshipping_warehouse_shippingmethods");
    $shippingmethods_template = $this->templates->get("padsmartshipping_warehouse_shippingmethod");
    $shippingmethods_pagetable->template_id = $shippingmethods_template->id;
    $shippingmethods_pagetable->save();
  }

  public function uninstall() {
    $padpages = $this->pages->find("template=padsmartshipping_warehouse_shippingmethod|padsmartshipping_warehouse, include=all");

    foreach($padpages as $p) {
      if($p->id) $this->pages->delete($p, true);
    }

    $templates = $this->getTemplateData();

    foreach($templates as $template_name => $template_data) {
      $t = $this->templates->get($template_name);
      if($t) $this->templates->delete($t);
      $fg = $this->fieldgroups->get($template_name);
      if($fg) $this->fieldgroups->delete($fg);
    }

    $fields = $this->getFieldData();

    foreach($fields as $field_name => $field_data) {
      $f = $this->fields->get($field_name);
      if($f) {
        $f->flags = Field::flagSystemOverride;
        $f->flags = 0;
        $this->fields->delete($f);
      }
    }
  }

  private function getFieldData() {
    $fields_json = file_get_contents(__DIR__ . "/data/warehouses_fields.json");
    return json_decode($fields_json, true);
  }

  private function getTemplateData() {
    $templates_json = file_get_contents(__DIR__ . "/data/warehouses_templates.json");
    return json_decode($templates_json, true);
  }
}
